### ISSUE TITLE
Can't install Python 3.11

### ISSUE THREAD

**Issue by niccolomineo** [jdxcode/rtx#465]
**Describe the bug**

```
~ $ rtx install python@3.11
Downloading python-build...
fatal: could not create leading directories of '/Users/nicco
Support/rtx/plugins/python/pyenv': Permission denied
rtx python@3.11 installing                                                 ✗ 0s rtx failed to install python@3.11
rtx Run with RTX_DEBUG=1 for more information
```

**To Reproduce**
- Do `rtx install python@3.11`

Tested on Mac Os 13.3.1 and rtx 1.28.1 macos-arm64 (ef91f0f 2023-04-09)

**Expected behavior**
I should be able to install python 3.11 successfully.

**`rtx doctor` output**

```bash
rtx version:
  1.28.1 macos-arm64 (ef91f0f 2023-04-09)

build:
  Target: aarch64-apple-darwin
  Features: SELF_UPDATE
  Built: Sun, 09 Apr 2023 23:05:19 +0000
  Rust Version: rustc 1.68.2 (9eb3afe9e 2023-03-27)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin22.0)

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "trusted_config_paths": "[]", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/nicco/.tool-versions

plugins:
  node     https://github.com/rtx-plugins/rtx-nodejs.git#946dc23
  nodejs   https://github.com/rtx-plugins/rtx-nodejs.git#946dc23
  python   https://github.com/rtx-plugins/rtx-python.git#2b29b16

toolset:
  node@19, nodejs@19, python@3.11

No problems found
```

**Comment by jdxcode** [comment]
what's the output of `rtx i python@3.11 --trace`?

**Comment by jdxcode** [comment]
it looks like a permissions issue on your machine

**Comment by jdxcode** [comment]
I think I found the problem and fixed it in https://github.com/jdxcode/rtx/commit/8ca30bf7074b6cc36b1d57263aadfa31dd796367

**Comment by niccolomineo** [comment]
> I think I found the problem and fixed it in [8ca30bf](https://github.com/jdxcode/rtx/commit/8ca30bf7074b6cc36b1d57263aadfa31dd796367)

```bash
~ $ rtx install python@3.11                                            11:15:09
From https://github.com/pyenv/pyenv
   b613a4ab..20189ff0  master     -> origin/master
 * [new tag]           v2.3.17    -> v2.3.17
python-build: definition not found: 3.11
From https://github.com/pyenv/pyenv
   b613a4ab..20189ff0  master     -> origin/master
 * [new tag]           v2.3.17    -> v2.3.17
python-build 3.11 /Users/nicco/.local/share/rtx/installs/python/3.11
python-build: definition not found: 3.11
rtx python@3.11 python-build 3.11 /Users/nicco/.local/share/rtx/installs/p ✗ 1s rtx failed to install python@3.11
rtx Run with RTX_DEBUG=1 for more information

~ $ rtx i python@3.11 --trace                                                                         11:15:47
[TRACE] (1) rtx::config::config_file::rtx_toml: [src/config/config_file/rtx_toml.rs:59] parsing: /Users/nicco/.config/rtx/config.toml
[TRACE] (3) rtx::config::config_file::rtx_toml: [src/config/config_file/rtx_toml.rs:59] parsing: /Users/nicco/.config/rtx/config.toml
[TRACE] (6) rtx::config::config_file::tool_versions: [src/config/config_file/tool_versions.rs:56] parsing tool-versions: /Users/nicco/.tool-versions
[TRACE] (1) rtx::config: [src/config/mod.rs:70] Settings: Settings {
    experimental: false,
    missing_runtime_behavior: Warn,
    always_keep_download: false,
    legacy_version_file: true,
    plugin_autoupdate_last_check_duration: 604800s,
    trusted_config_paths: [],
    verbose: true,
    asdf_compat: false,
    jobs: 4,
    shorthands_file: None,
    disable_default_shorthands: false,
    log_level: Trace,
    shims_dir: None,
    raw: false,
}
[TRACE] (3) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/python/legacy_filenames.msgpack.z
[TRACE] (4) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/node/legacy_filenames.msgpack.z
[TRACE] (6) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/nodejs/legacy_filenames.msgpack.z
[DEBUG] Files: ~/.tool-versions, ~/.config/rtx/config.toml
Installed Plugins: heroku-cli, jq, node, nodejs, python
[DEBUG] /Users/nicco/.local/share/rtx/bin/rtx i python@3.11 --trace
[TRACE] (3) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/node/remote_versions.msgpack.z
[TRACE] (5) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/python/remote_versions.msgpack.z
[TRACE] (4) rtx::cache: [src/cache.rs:78] reading ~/Library/Caches/rtx/nodejs/remote_versions.msgpack.z
[DEBUG] node@19, nodejs@19, python@3.11
[TRACE] (12) rtx::file: [src/file.rs:37] mkdir -p /Users/nicco/Library/Caches/rtx/lockfiles
[TRACE] (12) rtx::file: [src/file.rs:20] rm -rf /Users/nicco/Library/Caches/rtx/python/3.11
[TRACE] (12) rtx::file: [src/file.rs:37] mkdir -p /Users/nicco/.local/share/rtx/installs/python/3.11
[TRACE] (12) rtx::file: [src/file.rs:37] mkdir -p /Users/nicco/.local/share/rtx/downloads/python/3.11
[TRACE] (12) rtx::file: [src/file.rs:37] mkdir -p /Users/nicco/Library/Caches/rtx/python/3.11
rtx python@3.11 installing
[DEBUG] $ /Users/nicco/.local/share/rtx/plugins/python/bin/install 
rtx python@3.11 python-build 3.11 /Users/nicco/.local/share/rtx/installs/python/3.11
python-build: definition not found: 3.11
[TRACE] (12) rtx::file: [src/file.rs:20] rm -rf /Users/nicco/.local/share/rtx/installs/python/3.11
[TRACE] (12) rtx::file: [src/file.rs:20] rm -rf /Users/nicco/.local/share/rtx/downloads/python/3.11
Error: 
   0: failed to install python@3.11
   1: ~/.local/share/rtx/plugins/python/bin/install exited with non-zero status: exit code 2

Location:
   /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/convert/mod.rs:726

Version:
   1.28.3 macos-arm64 (f49f2ce 2023-04-10)

Suggestion: Run with RTX_DEBUG=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by jdxcode** [comment]
I can't reproduce, it is strange that it's not mapping `3.11` to the aliased version. What is the output of `rtx ls` and `ls -l ~/.local/share/installs/python`?

**Comment by niccolomineo** [comment]
> I can't reproduce, it is strange that it's not mapping `3.11` to the aliased version. What is the output of `rtx ls` and `ls -l ~/.local/share/installs/python`?

```bash
~ $ rtx ls                                                             20:12:31
node   19.8.1         ~/.tool-versions 19
nodejs 19.8.1         ~/.tool-versions 19
python 3.11 (missing) ~/.tool-versions 3.11
python 3.11.2        

~ $ ls -l ~/.local/share/installs/python                               20:12:43
ls: /Users/nicco/.local/share/installs/python: No such file or directory
```

**Comment by jdxcode** [comment]
ok I think I found the root cause and put a patch in

**Comment by niccolomineo** [comment]
Installation went through, this time. 👌 Thanks.

There's just one issue at the end, but it does not prevent the Python version I am installing from being usable:

```
~ $ rtx install python@3.11                                            09:54:44
Downloading openssl-1.1.1s.tar.gz...
-> https://www.openssl.org/source/openssl-1.1.1s.tar.gz
Installing openssl-1.1.1s...
Installed openssl-1.1.1s to /Users/nicco/.local/share/rtx/installs/python/3.11.3
Downloading readline-8.2.tar.gz...
-> https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
Installing readline-8.2...
Installed readline-8.2 to /Users/nicco/.local/share/rtx/installs/python/3.11.3
Downloading Python-3.11.3.tar.xz...
-> https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tar.xz
Installing Python-3.11.3...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nicco/.local/share/rtx/installs/python/3.11.3/lib/python3.11/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.11.3 to /Users/nicco/.local/share/rtx/installs/python/3.11.3
rtx python@3.11.3 python-build: use zlib from xcode sdk                    ✓ 3m
```

**Comment by niccolomineo** [comment]
> see https://gist.github.com/iandanforth/f3ac42b0963bcbfdf56bb446e9f40a33

Ok, but why is that so? In my case, choosing `rtx` should mean doing without `brew` completely.

**Comment by jdxcode** [comment]
That is not a design goal of this project. This is for _runtime_ management, not library management.
