### ISSUE TITLE
cannot install python@latest

### ISSUE THREAD

**Issue by sarahspak** [jdxcode/rtx#825]
**Describe the bug**
`rtx install python@latest` does not work. 

**To Reproduce**
```
brew install openssl readline sqlite3 xz zlib tcl-tk

rtx install python@latest
```

**Expected behavior**
Expected rtx to be able to install the latest version of python (3.11.4) without issue.

**`rtx doctor` output**
```
> rtx doctor
rtx version:
  2023.8.2 macos-arm64 (48df67e 2023-08-18)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Fri, 18 Aug 2023 15:59:38 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin22.0)

rtx data directory:
  /Users/sarahpak/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /Users/sarahpak/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  node@18

No problems found
```

**Additional context**
From stderr:
```
> rtx install python@latest
Downloading Python-3.11.4.tar.xz...
-> https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...
BUILD FAILED (OS X 13.4.1 using python-build 2.3.24)
Inspect or clean up the working tree at /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595
Results logged to /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595.log
Last 10 log lines:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595/Python-3.11.4/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595/Python-3.11.4/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [install] Error 1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.11.4.tar.xz...
-> https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.4.1 using python-build 2.3.24)

Inspect or clean up the working tree at /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595
Results logged to /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595.log

Last 10 log lines:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595/Python-3.11.4/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821023637.90595/Python-3.11.4/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [install] Error 1
rtx python@3.11.4 [ERROR] /Users/sarahpak/Library/Caches/rtx/python/pyenv/plugins/python-build/bin/python-build failed                                                                                        ✗ 76srtx /Users/sarahpak/Library/Caches/rtx/python/pyenv/plugins/python-build/bin/python-build exited with non-zero status: exit code 1
rtx Run with RTX_DEBUG=1 for more information
```

**Comment by dfang** [comment]
can you try this ?

https://stackoverflow.com/a/51902409

or 

```
~/Library/Caches/rtx/python/pyenv/bin/pyenv install 3.11.4 --debug
```

**Comment by sarahspak** [comment]
`PYTHONHOME` is not set in my env, so I tried the second suggestion but no luck


```
> ~/Library/Caches/rtx/python/pyenv/bin/pyenv install 3.11.4 --debug
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.11.4...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.5.1 using python-build 2.3.24)

Inspect or clean up the working tree at /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821172918.64533
Results logged to /var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821172918.64533.log

Last 10 log lines:
    return _get_module_details(pkg_main_name, error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821172918.64533/Python-3.11.4/Lib/runpy.py", line 112, in _get_module_details
    __import__(pkg_name)
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821172918.64533/Python-3.11.4/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/private/var/folders/8l/369lcxws2hz0q_cn2532qz080000gn/T/python-build.20230821172918.64533/Python-3.11.4/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [install] Error 1
```

**Comment by jdxcode** [comment]
maybe try unsetting `LD_LIBRARY_PATH` if set

**Comment by jdxcode** [comment]
I would also try running python-build by itself to rule out rtx doing anything here

**Comment by sarahspak** [comment]
Yup it's a pyenv issue
